export {default as ArrowRightIcon} from "./arrow-right.svg"
export {default as YoutubeIcon} from "./youtube.svg"
export {default as FacebookIcon} from "./facebook.svg"
export {default as TwitterIcon} from "./twitter.svg"
export {default as InstagramIcon} from "./instagram.svg"
export {default as GmalIcon} from "./gmail.svg"
export {default as GithubIcon} from "./github.svg"
export {default as DiscordIcon} from "./discord.svg"
export {default as AppleIcon} from "./apple.svg"

