import type { Metadata } from 'next';
import { Libre_Franklin } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/navbar';
import Footer from './components/footer/footer';
import FooterLink from './components/footerLink/footerLink';

const libre = Libre_Franklin({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Lepak Blogs Page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libre.className}>
        <Navbar />
        <div className="container">
          {children}
          <FooterLink />
        </div>
        <Footer />
      </body>
    </html>
  );
}
